# conda environment description file for MOHID-Cmd package testing environment
#
# Creates a conda environment in which the MOHID-Cmd package unit tests and
# coverage analysis can be run.
# Primarily intended for creation of a conda env for use in a GitHub Actions workflow.

name: mohid-cmd-test

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - attrs
  - cliff
  - cookiecutter
  - f90nml
  - gitpython
  - pandas
  - pip
  - pyyaml

  # For unit tests and coverage monitoring
  - pytest
  - pytest-cov

  # For documentation
  - sphinx
  - sphinx_rtd_theme

  - pip:
    - python-hglib

    # For unit tests
    - pytest-randomly
