# conda environment description file for docs build environment
# on readthedocs.org

name: sphinx-build

channels:
  - conda-forge
  - nodefaults

dependencies:
  - pip
  - python=3.9

  # RTD packages
  - mock
  - pillow
  - sphinx
  - sphinx_rtd_theme
