# conda environment description file for MOHID-Cmd package
# development environment
#
# Create a conda environment for development, testing and documentation of the package
# with:
#
#   $ conda env create -f MOHID-Cmd/envs/environment-dev.yaml
#   $ conda activate mohid-cmd
#   (mohid-cmd)$ python3 -m pip install --editable NEMO-Cmd
#   (mohid-cmd)$ python3 -m pip install --editable MOHID-Cmd
#
# The environment will include all of the tools used to develop,
# test, and document the MOHID-Cmd package.
#
# See the envs/requirements.txt file for an exhaustive list of all of the
# packages installed in the environment and their versions used in
# recent development.

name: mohid-cmd

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - attrs
  - cliff
  - cookiecutter
  - f90nml
  - gitpython
  - pandas
  - pip
  - python=3.9
  - pyyaml

  # For code style & repo QA
  - pre-commit

  # For unit tests
  - pytest
  - pytest-cov

  # For documentation
  - sphinx
  - sphinx_rtd_theme

  - pip:
    - python-hglib

    # For unit tests
    - pytest-randomly
