# conda environment description file for MOHID-Cmd package
# development environment
#
# Create a conda environment for development, testing and documentation of the package
# with:
#
#   $ conda env create -f MOHID-Cmd/envs/environment-dev.yaml
#   $ conda activate mohid-cmd
#   (mohid-cmd)$ python3 -m pip install --editable NEMO-Cmd
#   (mohid-cmd)$ python3 -m pip install --editable MOHID-Cmd
#
# The environment will include all of the tools used to develop,
# test, and document the MOHID-Cmd package.
#
# See the requirements.txt file for an exhaustive list of all of the
# packages installed in the environment and their versions used in
# recent development.

name: mohid-cmd

channels:
  - conda-forge
  - defaults

dependencies:
  - arrow
  - attrs
  - cliff!=2.9.0
  - cookiecutter
  - f90nml
  - gitpython
  - pandas
  - python-hglib
  - pip
  - python>=3.6
  - pyyaml

  # For unit tests
  - coverage
  - pytest

  # For documentation
  - sphinx
  - sphinx_rtd_theme

  # For coding style
  - black
